"""parent added to transaction category

Revision ID: b54259125484
Revises: seed_data_initial
Create Date: 2026-04-25 12:31:04.327786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54259125484'
down_revision: Union[str, Sequence[str], None] = 'seed_data_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_category', sa.Column('parent', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'transaction_category', 'user', ['parent'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_category', type_='foreignkey')
    op.drop_column('transaction_category', 'parent')
    # ### end Alembic commands ###
